import {useState} from 'react';import {Link,useParams} from 'react-router-dom';import {FESTIVALS} from '../data/extra';import {products} from '../data/products';import {img} from '../utils';import ProductCard from '../components/ProductCard';
export const Collections=()=><div className="max-w-7xl mx-auto px-4 py-10"><h1 className="font-display text-3xl mb-6">Collections</h1><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{Object.entries(FESTIVALS).map(([k,[n]])=><Link key={k} to={`/collections/${k}`} className="relative aspect-[4/3] overflow-hidden group"><img loading="lazy" src={img('fest'+k,800,600)} alt={n} className="w-full h-full object-cover group-hover:scale-105 transition duration-500"/><span className="absolute inset-0 bg-black/40 grid place-items-center font-display text-3xl text-white">{n}</span></Link>)}</div></div>;
export function CollectionPage(){const {collection}=useParams(),[n,occ]=FESTIVALS[collection]||['Collection','Festive'];
return <div><div className="relative h-56 bg-surface"><img src={img('fest'+collection,1600,500)} alt="" className="absolute inset-0 w-full h-full object-cover"/><div className="absolute inset-0 bg-black/50 grid place-items-center font-display text-4xl text-white">{n}</div></div><div className="max-w-7xl mx-auto px-4 py-10 grid grid-cols-2 md:grid-cols-4 gap-4">{products.filter(p=>p.occasion===occ).map(p=><ProductCard key={p.id} p={p}/>)}</div></div>}
const Q=[['Occasion',['Wedding','Festive','Casual','Party','Office']],['Budget',['Under ₹4,000','Under ₹8,000','Any']],['Fabric',['Silk','Cotton','Linen','Organza','Chiffon','Georgette']]];
export function StyleFinder(){const [a,setA]=useState([]),[gift,setGift]=useState(false),s=a.length;
const [occ,bud,fab]=a,max=bud==='Under ₹4,000'?4000:bud==='Under ₹8,000'?8000:1e9,res=products.filter(p=>p.occasion===occ&&p.price<=max&&(!fab||p.fabric===fab)).slice(0,4);
return <div className="max-w-3xl mx-auto px-4 py-10"><h1 className="font-display text-3xl">{gift?'Find a saree for someone special':'NAYARA Style Finder'}</h1><label className="text-sm flex gap-2 mt-2"><input type="checkbox" checked={gift} onChange={e=>setGift(e.target.checked)}/>Gift mode</label>
{s<3?<div className="mt-8"><h2 className="mb-3 font-medium">{Q[s][0]}</h2><div className="flex flex-wrap gap-2">{Q[s][1].map(o=><button key={o} className="btn btn-line" onClick={()=>setA([...a,o])}>{o}</button>)}</div></div>
:<div className="mt-8"><p className="text-sm text-mute mb-4">Picked for you: {a.join(' · ')}</p>{res.length?<div className="grid grid-cols-2 gap-4">{res.map(p=><ProductCard key={p.id} p={p}/>)}</div>:<p>No match — try a wider budget.</p>}<button className="btn btn-line mt-6" onClick={()=>setA([])}>Start over</button></div>}</div>}
