import {useEffect,useState} from 'react';import {useParams,useNavigate} from 'react-router-dom';import {Heart,Star,Truck} from 'lucide-react';
import {productService} from '../services';import {useStore} from '../store';import {inr} from '../utils';import {Skeleton} from '../components/ui';import ProductCard from '../components/ProductCard';
export default function Product(){const {id}=useParams(),nav=useNavigate();const [p,setP]=useState(null),[all,setAll]=useState([]),[i,setI]=useState(0),[pin,setPin]=useState(''),[eta,setEta]=useState('');
const add=useStore(s=>s.addToCart),wished=useStore(s=>s.wishlist.includes(+id)),toggle=useStore(s=>s.toggleWish),view=useStore(s=>s.view),recent=useStore(s=>s.recent);
useEffect(()=>{setP(null);setI(0);productService.get(id).then(x=>{setP(x);view(+id);document.title=`${x?.name} | NAYARA`});productService.list().then(setAll)},[id]);
if(!p)return <div className="max-w-7xl mx-auto px-4 py-10 grid md:grid-cols-2 gap-10"><Skeleton className="aspect-[3/4]"/><div className="grid gap-4 content-start"><Skeleton className="h-8 w-2/3"/><Skeleton className="h-5 w-1/3"/><Skeleton className="h-24"/></div></div>;
const rows=[['SKU',p.sku],['Fabric',p.fabric],['Color',p.color],['Length',p.length+' + unstitched blouse'],['Occasion',p.occasion],['Care','Dry clean only']];
return <div className="max-w-7xl mx-auto px-4 py-8"><div className="grid md:grid-cols-2 gap-10">
<div className="grid grid-cols-[72px_1fr] gap-3"><div className="grid gap-2 content-start">{p.images.map((s,k)=><button key={k} onClick={()=>setI(k)} aria-label={`Image ${k+1}`} className={`border ${i===k?'border-ink':'border-line'}`}><img src={s} alt="" loading="lazy"/></button>)}</div><img src={p.images[i]} alt={p.name} className="w-full border border-line"/></div>
<div><h1 className="font-display text-3xl">{p.name}</h1><div className="flex items-center gap-2 text-sm text-mute mt-2"><Star size={14} fill="currentColor"/>{p.rating} · {p.reviews} reviews</div>
<div className="mt-4 flex items-baseline gap-3"><b className="text-2xl">{inr(p.price)}</b><s className="text-mute">{inr(p.mrp)}</s><span className="text-sm">{p.discount}% off</span></div>
<p className="text-xs text-mute mt-1">Inclusive of all taxes</p>
<dl className="mt-6 grid grid-cols-[110px_1fr] gap-y-2 text-sm border-t border-line pt-4">{rows.map(([k,v])=><div key={k} className="contents"><dt className="text-mute">{k}</dt><dd>{v}</dd></div>)}</dl>
<div className="flex gap-3 mt-6"><button className="btn btn-solid flex-1" onClick={()=>add(p.id)}>Add to bag</button><button className="btn btn-line flex-1" onClick={()=>{add(p.id);nav('/checkout')}}>Buy now</button>
<button aria-label="Wishlist" aria-pressed={wished} onClick={()=>toggle(p.id)} className="border border-line px-3"><Heart fill={wished?'rgb(var(--rose))':'none'} stroke={wished?'rgb(var(--rose))':'currentColor'}/></button></div>
<div className="mt-6 border border-line p-4 text-sm"><label className="flex items-center gap-2 font-medium mb-2"><Truck size={16}/>Check delivery</label><div className="flex gap-2"><input className="input" inputMode="numeric" maxLength={6} placeholder="Pincode" value={pin} onChange={e=>setPin(e.target.value)}/><button className="btn btn-line" onClick={()=>setEta(pin.length===6?'Delivery in 3–5 days':'Enter a valid 6-digit pincode')}>Check</button></div>{eta&&<p className="mt-2 text-mute">{eta}</p>}</div></div></div>
<h2 className="font-display text-2xl mt-16 mb-4">Similar sarees</h2><div className="grid grid-cols-2 md:grid-cols-4 gap-4">{all.filter(x=>x.fabric===p.fabric&&x.id!==p.id).slice(0,4).map(x=><ProductCard key={x.id} p={x}/>)}</div>
{recent.length>1&&<><h2 className="font-display text-2xl mt-16 mb-4">Recently viewed</h2><div className="grid grid-cols-2 md:grid-cols-4 gap-4">{recent.filter(r=>r!==+id).slice(0,4).map(r=>all.find(x=>x.id===r)).filter(Boolean).map(x=><ProductCard key={x.id} p={x}/>)}</div></>}</div>}
