import {useEffect,useState} from 'react';import {useParams,Link} from 'react-router-dom';import {useForm} from 'react-hook-form';import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip,CartesianGrid} from 'recharts';
import {MODS} from '../data/extra';import {adminService} from '../services';import Soon from './Soon';
export function Module(){const {mod}=useParams(),m=MODS[mod];const [rows,setRows]=useState(null),[q,setQ]=useState('');useEffect(()=>{setRows(m?m.rows():null);setQ('')},[mod]);
if(!m)return <Soon/>;if(!rows)return null;const shown=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase()));
return <div><div className="flex justify-between gap-3 mb-4"><h1 className="text-xl font-semibold capitalize">{mod}</h1><input className="input !w-56" placeholder="Search" aria-label="Search" value={q} onChange={e=>setQ(e.target.value)}/></div>
<div className="bg-bg border border-line overflow-x-auto"><table className="w-full text-sm"><thead className="text-left text-mute border-b border-line"><tr>{m.cols.map(c=><th key={c} className="p-3 font-medium capitalize">{c}</th>)}{m.act&&<th className="p-3">Actions</th>}</tr></thead><tbody>
{shown.map((r,i)=><tr key={i} className="border-b border-line hover:bg-hover">{m.cols.map(c=><td key={c} className={`p-3 ${r[c]==='Low stock'?'text-red-600/80':''}`}>{r[c]}</td>)}{m.act&&<td className="p-3">{m.act.map(a=><button key={a} className="text-xs underline mr-3" onClick={()=>setRows(rs=>a==='Delete'?rs.filter(x=>x!==r):rs.map(x=>x===r?{...x,status:a}:x))}>{a}</button>)}</td>}</tr>)}</tbody></table></div></div>}
export function Analytics(){const [d,setD]=useState([]);useEffect(()=>{adminService.revenue().then(setD)},[]);
return <div><h1 className="text-xl font-semibold mb-6">Analytics</h1><div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[['Avg order value','₹2,840'],['Conversion','3.2%'],['Cart abandonment','68%'],['Returning customers','41%']].map(([k,v])=><div key={k} className="bg-bg border border-line p-4"><div className="text-xs text-mute">{k}</div><div className="text-2xl font-semibold">{v}</div></div>)}</div>
<div className="bg-bg border border-line p-4 mt-6 h-72"><div className="text-sm font-medium mb-2">Orders by month</div><ResponsiveContainer width="100%" height="90%"><BarChart data={d}><CartesianGrid stroke="rgb(var(--line))" vertical={false}/><XAxis dataKey="m" stroke="rgb(var(--mute))" fontSize={12}/><YAxis stroke="rgb(var(--mute))" fontSize={12}/><Tooltip contentStyle={{background:'rgb(var(--bg))',border:'1px solid rgb(var(--line))'}}/><Bar dataKey="orders" fill="rgb(var(--ink))"/></BarChart></ResponsiveContainer></div></div>}
const FIELDS=['Product name','SKU','Description','Category','Collection','MRP','Selling price','Tax','Stock','Low-stock threshold','Fabric','Color','Pattern','Occasion','Weave','Length','Blouse type','Region'];
export function ProductForm(){const {register,handleSubmit,formState:{errors}}=useForm(),[files,setFiles]=useState([]),[ok,setOk]=useState(false);
return <form onSubmit={handleSubmit(()=>setOk(true))} className="max-w-3xl"><div className="flex justify-between mb-4"><h1 className="text-xl font-semibold">New product</h1><Link to="/admin/products" className="text-sm underline">Back</Link></div>
<div className="grid sm:grid-cols-2 gap-3">{FIELDS.map(f=><label key={f} className="text-xs text-mute grid gap-1">{f}<input className="input" {...register(f,{required:['Product name','SKU','MRP','Selling price'].includes(f)&&'Required'})} aria-invalid={!!errors[f]}/>{errors[f]&&<span role="alert" className="text-red-600/80">{errors[f].message}</span>}</label>)}</div>
<div onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();setFiles(x=>[...x,...[...e.dataTransfer.files].map(f=>f.name)])}} className="border border-dashed border-line bg-bg p-8 text-center text-sm text-mute mt-4">Drag and drop images here{files.map(n=><div key={n}>{n}</div>)}</div>
<button className="btn btn-solid mt-4">Save product</button>{ok&&<p className="text-sm mt-2">Product saved (mock).</p>}</form>}
export function Settings(){return <div className="max-w-md grid gap-3"><h1 className="text-xl font-semibold">Settings</h1>{['Store name','Support email','GST number','Free shipping threshold'].map(l=><input key={l} className="input" placeholder={l} aria-label={l}/>)}<button className="btn btn-solid">Save settings</button></div>}
