import {lazy,Suspense,useEffect} from 'react';import {Routes,Route} from 'react-router-dom';import {useStore} from './store';import MainLayout from './layouts/MainLayout';import {Skeleton} from './components/ui';
const L=f=>lazy(f),N=(f,k)=>L(()=>f().then(m=>({default:m[k]})));
const Home=L(()=>import('./pages/Home')),Shop=L(()=>import('./pages/Shop')),Product=L(()=>import('./pages/Product')),Cart=L(()=>import('./pages/Cart')),Wishlist=L(()=>import('./pages/Wishlist')),Checkout=L(()=>import('./pages/Checkout')),Login=L(()=>import('./pages/Login')),Search=L(()=>import('./pages/Search')),Account=L(()=>import('./pages/Account')),
Signup=N(()=>import('./pages/Auth'),'Signup'),Otp=N(()=>import('./pages/Auth'),'Otp'),Forgot=N(()=>import('./pages/Auth'),'Forgot'),NotFound=N(()=>import('./pages/Misc'),'NotFound'),
OrdersPage=N(()=>import('./pages/Orders'),'OrdersPage'),OrderDetail=N(()=>import('./pages/Orders'),'OrderDetail'),Invoice=N(()=>import('./pages/Orders'),'Invoice'),
Collections=N(()=>import('./pages/Extras'),'Collections'),CollectionPage=N(()=>import('./pages/Extras'),'CollectionPage'),StyleFinder=N(()=>import('./pages/Extras'),'StyleFinder'),
AdminLayout=L(()=>import('./admin/AdminLayout')),Dashboard=L(()=>import('./admin/Dashboard')),AProducts=L(()=>import('./admin/Products')),Module=N(()=>import('./admin/Modules'),'Module'),Analytics=N(()=>import('./admin/Modules'),'Analytics'),ProductForm=N(()=>import('./admin/Modules'),'ProductForm'),Settings=N(()=>import('./admin/Modules'),'Settings');
export default function App(){const theme=useStore(s=>s.theme);useEffect(()=>{document.documentElement.classList.toggle('dark',theme==='dark')},[theme]);
return <Suspense fallback={<div className="p-10"><Skeleton className="h-64"/></div>}><Routes><Route element={<MainLayout/>}><Route index element={<Home/>}/><Route path="shop" element={<Shop/>}/><Route path="shop/:category" element={<Shop/>}/><Route path="collections" element={<Collections/>}/><Route path="collections/:collection" element={<CollectionPage/>}/><Route path="product/:id" element={<Product/>}/><Route path="search" element={<Search/>}/><Route path="style-finder" element={<StyleFinder/>}/><Route path="cart" element={<Cart/>}/><Route path="wishlist" element={<Wishlist/>}/><Route path="checkout" element={<Checkout/>}/><Route path="order-success" element={<OrdersPage/>}/><Route path="orders" element={<OrdersPage/>}/><Route path="orders/:id" element={<OrderDetail/>}/><Route path="track-order" element={<OrderDetail/>}/><Route path="invoice/:id" element={<Invoice/>}/>
<Route path="login" element={<Login/>}/><Route path="signup" element={<Signup/>}/><Route path="forgot-password" element={<Forgot/>}/><Route path="verify-otp" element={<Otp/>}/><Route path="account" element={<Account/>}/><Route path="account/:tab" element={<Account/>}/><Route path="*" element={<NotFound/>}/></Route>
<Route path="admin" element={<AdminLayout/>}><Route index element={<Dashboard/>}/><Route path="products" element={<AProducts/>}/><Route path="products/new" element={<ProductForm/>}/><Route path="products/:id" element={<ProductForm/>}/><Route path="analytics" element={<Analytics/>}/><Route path="settings" element={<Settings/>}/><Route path=":mod" element={<Module/>}/><Route path="orders/:id" element={<Module/>}/><Route path="customers/:id" element={<Module/>}/></Route></Routes></Suspense>}
